name: deploy-auth
on:
    push:
        branches: 
            - master 
        paths: 
            - 'auth/**'
jobs: 
    build:
        runs-on: ubuntu-latest 
        steps: 
            - uses: actions/checkout@v2 
            - run: cd auth && docker build -t ozshm/auth .
            - run: 
                echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME
              env: 
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
            - run: docker push ozshm/auth
