name: deploy-expiration
on:
    push:
        branches: 
            - master 
        paths: 
            - 'expiration/**'
jobs: 
    build:
        runs-on: ubuntu-latest 
        steps: 
            - uses: actions/checkout@v2 
            - run: cd expiration && docker build -t ozshm/expiration:1.0 .
            - 
              name: Login to Docker hub
              uses: docker/login-action@v2 
              with: 
                 username: ${{ secrets.DOCKER_USERNAME }}
                 password: ${{ secrets.DOCKER_TOKEN }} 
            - run: docker push ozshm/expiration
            - uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            - 
              name: Changing context to kubernetes cluster-ticketing on Digital Ocean
              run: doctl kubernetes cluster kubeconfig save ticketing
            - run: kubectl rollout restart deployment expiration-depl
