name: deploy-manifests
on:
    push:
        branches: 
            - master 
        paths: 
            - 'infra/**'
jobs: 
    build:
        runs-on: ubuntu-latest 
        steps: 
            - uses: actions/checkout@v2 
            - uses: digitalocean/action-doctl@v2
              with:
                token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            - 
              name: Changing context to kubernetes cluster-ticketing on Digital Ocean
              run: doctl kubernetes cluster kubeconfig save ticketing
            - run: kubectl apply -f infra/k8s
